/*
  course-lessons.js — the first four lessons, PRE-GENERATED by the model
  (NVIDIA NIM) from source-material.js and validated. Generated by gen-course.js.
  The course plays these in order, then falls back to live generation.
  Regenerate any time with:  node gen-course.js
*/
const COURSE_LESSONS = [
  {
    "id": "london-foundations",
    "title": "The London System: Your First Solid Opening",
    "subtitle": "Learn the d4-e3-c3 pawn triangle and why the bishop goes to f4 first.",
    "steps": [
      {
        "type": "teach",
        "title": "What is the London System?",
        "body": "The London System is a <strong>system</strong> for White: you aim for the same solid setup against almost anything Black plays. Instead of memorizing long forcing lines, you focus on a reliable pawn triangle and active piece development."
      },
      {
        "type": "teach",
        "title": "The Pawn Triangle",
        "body": "The backbone of the London is the pawn triangle: pawns on <strong>d4, e3, and c3</strong>. This gives White a sturdy center with no weaknesses and supports the key e5 square for a knight."
      },
      {
        "type": "teach",
        "title": "The Active Bishop on f4",
        "body": "The defining feature is developing the queen's bishop to <strong>f4</strong> before playing e3. If you play e3 first, the bishop is trapped behind the pawn chain and becomes passive. On f4 it eyes e5, c7, and the b8-h2 diagonal."
      },
      {
        "type": "teach",
        "title": "A Natural Move Order",
        "body": "A typical London move order is: 1.d4, 2.Bf4, 3.e3, 4.Nf3, 5.Bd3, 6.Nbd2, 7.c3, then castle. Let's see it on the board."
      },
      {
        "type": "teach",
        "title": "Building the Setup",
        "body": "Watch how White builds the pawn triangle and develops the pieces in a natural order.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "Central pawn"
            },
            {
              "from": "d7",
              "to": "d5",
              "san": "1... d5",
              "note": "Black centralizes"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop!"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "2... Nf6",
              "note": "Develops knight"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Pawn triangle"
            },
            {
              "from": "e7",
              "to": "e6",
              "san": "3... e6",
              "note": "Solid setup"
            },
            {
              "from": "g1",
              "to": "f3",
              "san": "4. Nf3",
              "note": "Develops knight"
            },
            {
              "from": "f8",
              "to": "d6",
              "san": "4... Bd6",
              "note": "Attacks f4-bishop"
            },
            {
              "from": "f4",
              "to": "g3",
              "san": "5. Bg3",
              "note": "Preserves bishop"
            },
            {
              "from": "e8",
              "to": "g8",
              "san": "5... O-O",
              "note": "Black castles"
            },
            {
              "from": "f1",
              "to": "d3",
              "san": "6. Bd3",
              "note": "Aims at h7"
            },
            {
              "from": "b8",
              "to": "c6",
              "san": "6... Nc6",
              "note": "Develops knight"
            },
            {
              "from": "b1",
              "to": "d2",
              "san": "7. Nbd2",
              "note": "Supports e4"
            },
            {
              "from": "c7",
              "to": "c5",
              "san": "7... c5",
              "note": "Challenges center"
            },
            {
              "from": "c2",
              "to": "c3",
              "san": "8. c3",
              "note": "Completes triangle"
            }
          ]
        }
      },
      {
        "type": "check",
        "concept": "active-bishop",
        "question": "Why must White develop the queen's bishop to f4 before playing e3?",
        "options": [
          {
            "text": "Because e3 blocks the bishop's diagonal, making it passive",
            "correct": true,
            "insight": "Correct! If you play e3 first, the c1-bishop is stuck behind the pawn chain. The whole point of the London is to get that bishop active on f4."
          },
          {
            "text": "Because the bishop attacks the black queen immediately",
            "correct": false,
            "miss": "overrating-immediate-threat",
            "insight": "The bishop on f4 doesn't attack the queen yet. Its value is long-term: it eyes key squares and supports the center."
          },
          {
            "text": "Because the move order never matters in a system",
            "correct": false,
            "miss": "move-order-never-matters",
            "insight": "Move order does matter! Playing e3 first traps the bishop. The London is a system, but you must follow the right sequence."
          }
        ]
      },
      {
        "type": "check",
        "concept": "pawn-triangle",
        "question": "What is the main advantage of the d4-e3-c3 pawn triangle?",
        "options": [
          {
            "text": "It gives White a sturdy center with no weaknesses",
            "correct": true,
            "insight": "Exactly! The triangle is solid and supports the key e5 square for a knight, making it hard for Black to attack quickly."
          },
          {
            "text": "It allows White to attack the black king immediately",
            "correct": false,
            "miss": "overrating-immediate-threat",
            "insight": "The triangle is defensive, not an immediate attacking weapon. The attack comes later, after development."
          },
          {
            "text": "It prevents Black from playing ...c5",
            "correct": false,
            "miss": "forgetting-b2-loose",
            "insight": "The triangle does not stop ...c5. In fact, ...c5 is a common and critical reply from Black, especially with ...Qb6 targeting the loose b2-pawn."
          }
        ]
      },
      {
        "type": "teach",
        "title": "The Critical ...Qb6 Counter",
        "body": "Because the bishop leaves c1, the b2-pawn becomes undefended. Black can test you with an early ...c5 and ...Qb6, attacking b2. Here's the key line."
      },
      {
        "type": "teach",
        "title": "Black's Testing Reply",
        "body": "Watch how Black immediately pressures the b2-pawn after White develops the bishop.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "Central pawn"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "1... Nf6",
              "note": "Develops knight"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop"
            },
            {
              "from": "c7",
              "to": "c5",
              "san": "2... c5",
              "note": "Challenges center"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Pawn triangle"
            },
            {
              "from": "d8",
              "to": "b6",
              "san": "3... Qb6",
              "note": "Attacks b2!"
            }
          ]
        }
      },
      {
        "type": "check",
        "concept": "qb6-counter",
        "question": "After 1.d4 Nf6 2.Bf4 c5 3.e3, why is ...Qb6 a dangerous reply for Black?",
        "options": [
          {
            "text": "Because the b2-pawn is no longer defended by the bishop, and ...Qb6 attacks it",
            "correct": true,
            "insight": "Correct! The bishop left c1, so b2 is loose. Black's queen attacks it, and White must be ready to defend or counter-attack."
          },
          {
            "text": "Because ...Qb6 threatens immediate checkmate",
            "correct": false,
            "miss": "overrating-immediate-threat",
            "insight": "There's no checkmate threat. The danger is the b2-pawn, not a quick mate."
          },
          {
            "text": "Because ...Qb6 forces White to play Bd3 immediately",
            "correct": false,
            "miss": "playing-bd3-autopilot",
            "insight": "Bd3 doesn't help against ...Qb6. White needs to deal with the b2 threat, not develop the light-squared bishop automatically."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Summary: The London's Core Ideas",
        "body": "The London System gives you a solid, repeatable setup: the d4-e3-c3 pawn triangle, the active bishop on f4 (before e3), and a knight often heading to e5. It's easy to learn but requires understanding when to adapt, like choosing Bd3 vs Be2 or handling ...Qb6. You're ready to build from here!"
      }
    ]
  },
  {
    "id": "london-e5-plan",
    "title": "The Knight on e5 and the Kingside Attack",
    "subtitle": "White's main strategic goal and the Greek-gift sacrifice",
    "steps": [
      {
        "type": "teach",
        "title": "The Knight on e5: White's Dream Outpost",
        "body": "In the London System, White's main strategic goal is to plant a knight on e5, supported by the d4-pawn. From e5 the knight is powerful and hard to challenge, and it supports a kingside buildup."
      },
      {
        "type": "teach",
        "title": "Building the Setup",
        "body": "To reach e5, White first builds the d4-e3-c3 pawn triangle and develops pieces: Bf4, e3, Nf3, Bd3, Nbd2, and c3. Then the knight on f3 can jump to e5, often after Black has played ...c5 or ...Nc6."
      },
      {
        "type": "check",
        "concept": "knight-on-e5",
        "question": "Why is planting a knight on e5 a key goal for White in the London System?",
        "options": [
          {
            "text": "The knight on e5 is supported by the d4-pawn and can't be easily chased away, allowing White to build a kingside attack.",
            "correct": true,
            "insight": "Correct! The d4-pawn defends e5, and the knight there is a powerful outpost for attacking Black's king."
          },
          {
            "text": "The knight on e5 attacks the black queen directly, forcing Black to waste time defending.",
            "correct": false,
            "miss": "knight-on-e5",
            "insight": "Not quite. The knight on e5 doesn't directly attack the queen; its value is in controlling key squares and supporting kingside pressure."
          },
          {
            "text": "The knight on e5 is the only way White can create any threats in the London System.",
            "correct": false,
            "miss": "knight-on-e5",
            "insight": "The London has many plans, but the knight on e5 is the main strategic goal, not the only way to create threats."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Walkthrough: Building the Knight on e5",
        "body": "Let's see how White builds the standard setup and lands a knight on e5, then swings the queen toward the kingside.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "White's first move"
            },
            {
              "from": "d7",
              "to": "d5",
              "san": "1... d5",
              "note": "Black's solid reply"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop outside the pawn chain"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "2... Nf6",
              "note": "Black develops"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Completing the pawn triangle"
            },
            {
              "from": "e7",
              "to": "e6",
              "san": "3... e6",
              "note": "Black solid"
            },
            {
              "from": "g1",
              "to": "f3",
              "san": "4. Nf3",
              "note": "Knight heads for e5"
            },
            {
              "from": "c7",
              "to": "c5",
              "san": "4... c5",
              "note": "Black challenges d4"
            },
            {
              "from": "c2",
              "to": "c3",
              "san": "5. c3",
              "note": "Supporting d4"
            },
            {
              "from": "b8",
              "to": "c6",
              "san": "5... Nc6",
              "note": "Developing"
            },
            {
              "from": "b1",
              "to": "d2",
              "san": "6. Nbd2",
              "note": "Standard London knight"
            },
            {
              "from": "f8",
              "to": "d6",
              "san": "6... Bd6",
              "note": "Black attacks f4"
            },
            {
              "from": "f4",
              "to": "g3",
              "san": "7. Bg3",
              "note": "Preserving the good bishop"
            },
            {
              "from": "e8",
              "to": "g8",
              "san": "7... O-O",
              "note": "Black castles"
            },
            {
              "from": "f1",
              "to": "d3",
              "san": "8. Bd3",
              "note": "Aiming at h7"
            },
            {
              "from": "b7",
              "to": "b6",
              "san": "8... b6",
              "note": "Preparing Bb7"
            },
            {
              "from": "f3",
              "to": "e5",
              "san": "9. Ne5",
              "note": "Knight lands on e5!"
            },
            {
              "from": "c8",
              "to": "b7",
              "san": "9... Bb7",
              "note": "Black's fianchetto"
            },
            {
              "from": "d1",
              "to": "f3",
              "san": "10. Qf3",
              "note": "Queen joins the attack"
            }
          ]
        }
      },
      {
        "type": "teach",
        "title": "The Kingside Buildup: Qf3 and Qh5",
        "body": "With the knight on e5 and bishop on d3, White often brings the queen to f3 or h5, targeting h7. This setup can lead to a devastating Greek-gift sacrifice: Bxh7+! Kxh7, Ng5+ and Qh5, generating a dangerous attack."
      },
      {
        "type": "check",
        "concept": "greek-gift",
        "question": "What is the Greek-gift sacrifice in the London System?",
        "options": [
          {
            "text": "Sacrificing the bishop on h7 with Bxh7+ to expose the black king, followed by Ng5+ and Qh5 for a strong attack.",
            "correct": true,
            "insight": "Correct! This classic sacrifice works when Black has castled kingside and h7 is weak, often with a knight on e5 and bishop on d3."
          },
          {
            "text": "Sacrificing the knight on e5 to open lines for the queen and bishop.",
            "correct": false,
            "miss": "greek-gift",
            "insight": "No, the Greek gift involves sacrificing the bishop, not the knight. The knight on e5 supports the attack but isn't sacrificed."
          },
          {
            "text": "Trading the f4-bishop for Black's knight on f6 to weaken Black's kingside.",
            "correct": false,
            "miss": "greek-gift",
            "insight": "That's not the Greek gift. The f4-bishop is usually preserved with Bg3, not traded. The Greek gift is a bishop sacrifice on h7."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Walkthrough: The Greek-Gift Pattern",
        "body": "Here's a simplified example of the Greek-gift attack. White has the knight on e5, bishop on d3, and Black has castled kingside.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "White opens"
            },
            {
              "from": "d7",
              "to": "d5",
              "san": "1... d5",
              "note": "Black"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "2... Nf6",
              "note": "Black"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Pawn triangle"
            },
            {
              "from": "e7",
              "to": "e6",
              "san": "3... e6",
              "note": "Black"
            },
            {
              "from": "g1",
              "to": "f3",
              "san": "4. Nf3",
              "note": "Knight"
            },
            {
              "from": "f8",
              "to": "d6",
              "san": "4... Bd6",
              "note": "Black attacks f4"
            },
            {
              "from": "f4",
              "to": "g3",
              "san": "5. Bg3",
              "note": "Preserve bishop"
            },
            {
              "from": "e8",
              "to": "g8",
              "san": "5... O-O",
              "note": "Black castles"
            },
            {
              "from": "f1",
              "to": "d3",
              "san": "6. Bd3",
              "note": "Aiming at h7"
            },
            {
              "from": "b8",
              "to": "c6",
              "san": "6... Nc6",
              "note": "Black"
            },
            {
              "from": "f3",
              "to": "e5",
              "san": "7. Ne5",
              "note": "Knight on e5!"
            },
            {
              "from": "d8",
              "to": "e7",
              "san": "7... Qe7",
              "note": "Black defends"
            },
            {
              "from": "d1",
              "to": "h5",
              "san": "8. Qh5",
              "note": "Queen targets h7"
            },
            {
              "from": "h7",
              "to": "h6",
              "san": "8... h6",
              "note": "Black tries to stop Ng5"
            },
            {
              "from": "d3",
              "to": "h7",
              "san": "9. Bxh7+",
              "note": "Greek gift!"
            },
            {
              "from": "g8",
              "to": "h7",
              "san": "9... Kxh7",
              "note": "King takes"
            },
            {
              "from": "e5",
              "to": "g6",
              "san": "10. Ng5+",
              "note": "Forking king and queen"
            },
            {
              "from": "h7",
              "to": "g8",
              "san": "10... Kg8",
              "note": "Black retreats"
            },
            {
              "from": "h5",
              "to": "h7",
              "san": "11. Qh7#",
              "note": "Checkmate!"
            }
          ]
        }
      },
      {
        "type": "check",
        "concept": "kingside-attack",
        "question": "When should White consider playing Bd3 instead of Be2 in the London System?",
        "options": [
          {
            "text": "When Black has not played ...g6, so the bishop can aim at h7 and support the kingside attack.",
            "correct": true,
            "insight": "Correct! Bd3 is the main square because it aims at h7 and supports the attacking plan. But if Black fianchettoes with ...g6, Be2 is better."
          },
          {
            "text": "Always, because Bd3 is always better than Be2 in the London System.",
            "correct": false,
            "miss": "kingside-attack",
            "insight": "No, the source says 'Choosing between Bd3 and Be2 is a matter of positional judgment.' When Black plays ...g6, Be2 is better."
          },
          {
            "text": "When Black plays ...g6, because the bishop on d3 can attack the g6-pawn.",
            "correct": false,
            "miss": "kingside-attack",
            "insight": "Actually, when Black plays ...g6, the ...g6 pawn shields h7, so Bd3 loses its bite. In that case Be2 is more useful."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Summary: The Knight on e5 and the Greek Gift",
        "body": "Remember: White's main goal is to plant a knight on e5, supported by d4. From there, White builds a kingside attack with Qf3 or Qh5, and when Black castles and h7 is weak, the Greek-gift sacrifice Bxh7+ can be crushing. But always adapt: if Black plays ...g6, consider Be2 instead of Bd3."
      }
    ]
  },
  {
    "id": "london-qb6",
    "title": "The Critical ...c5 and ...Qb6 Counter",
    "subtitle": "Why 2.Bf4 first and how to handle Black's sharpest reply",
    "steps": [
      {
        "type": "teach",
        "title": "Why 2.Bf4 First?",
        "body": "Modern London players play <strong>2.Bf4</strong> before committing the knight to f3. If you play 2.Nf3 first, Black can play 2...c5 3.Bf4 cxd4 4.Nxd4 Nd7 and get easy, comfortable play. By playing Bf4 early, you keep flexibility and avoid that simplification."
      },
      {
        "type": "teach",
        "title": "The Loose b2-Pawn",
        "body": "Once the bishop leaves c1, the b2-pawn is no longer defended. Black's most critical plan is an early <strong>...c5</strong> followed by <strong>...Qb6</strong>, attacking b2. This is the heart of London theory."
      },
      {
        "type": "teach",
        "title": "The Critical Line in Action",
        "body": "Let's see the key line where Black immediately targets b2. White must be ready to defend or counter-attack.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "White's first move"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "1... Nf6",
              "note": "Black develops"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop before e3"
            },
            {
              "from": "c7",
              "to": "c5",
              "san": "2... c5",
              "note": "Challenges d4 and b2"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Supports d4, frees bishop"
            },
            {
              "from": "d8",
              "to": "b6",
              "san": "3... Qb6",
              "note": "Attacks loose b2!"
            }
          ]
        }
      },
      {
        "type": "check",
        "concept": "b2-loose",
        "question": "After 1.d4 Nf6 2.Bf4 c5 3.e3 Qb6, why is Black's queen attacking b2 dangerous?",
        "options": [
          {
            "text": "Because the bishop on f4 no longer defends b2, leaving it undefended.",
            "correct": true,
            "insight": "Correct! The bishop left c1, so b2 is loose. Black's queen targets it immediately."
          },
          {
            "text": "Because White forgot to move the b2-pawn forward.",
            "correct": false,
            "miss": "b2-loose",
            "insight": "No, the pawn didn't move—it's just undefended. The bishop's departure left it vulnerable."
          },
          {
            "text": "Because Black's queen threatens checkmate on b2.",
            "correct": false,
            "miss": "b2-loose",
            "insight": "Not checkmate—just a pawn grab. But losing a pawn is bad, so White must respond."
          }
        ]
      },
      {
        "type": "teach",
        "title": "How White Meets ...Qb6",
        "body": "White has several good answers: defend b2 with <strong>Qc1</strong> or <strong>Qb3</strong>, or counter-attack with <strong>Nc3</strong>. Sometimes White even allows ...Qxb2 in return for fast development and an attack. The key is to stay calm and not panic."
      },
      {
        "type": "teach",
        "title": "A Full Example with ...c5",
        "body": "Now let's see a longer line where White builds the standard setup and handles Black's ...c5 challenge. Watch how White keeps the bishop on f4, builds the pawn triangle, and later plants a knight on e5.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "White's first move"
            },
            {
              "from": "d7",
              "to": "d5",
              "san": "1... d5",
              "note": "Black responds"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "2... Nf6",
              "note": "Develops"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Pawn triangle"
            },
            {
              "from": "e7",
              "to": "e6",
              "san": "3... e6",
              "note": "Solid"
            },
            {
              "from": "g1",
              "to": "f3",
              "san": "4. Nf3",
              "note": "Knight to f3"
            },
            {
              "from": "c7",
              "to": "c5",
              "san": "4... c5",
              "note": "Challenges d4"
            },
            {
              "from": "c2",
              "to": "c3",
              "san": "5. c3",
              "note": "Supports d4"
            },
            {
              "from": "b8",
              "to": "c6",
              "san": "5... Nc6",
              "note": "Develops"
            },
            {
              "from": "b1",
              "to": "d2",
              "san": "6. Nbd2",
              "note": "Knight to d2"
            },
            {
              "from": "f8",
              "to": "d6",
              "san": "6... Bd6",
              "note": "Trades bishops?"
            },
            {
              "from": "f4",
              "to": "g3",
              "san": "7. Bg3",
              "note": "Sidesteps trade"
            },
            {
              "from": "e8",
              "to": "g8",
              "san": "7... O-O",
              "note": "Black castles"
            },
            {
              "from": "f1",
              "to": "d3",
              "san": "8. Bd3",
              "note": "Aims at h7"
            },
            {
              "from": "b7",
              "to": "b6",
              "san": "8... b6",
              "note": "Prepares Bb7"
            },
            {
              "from": "f3",
              "to": "e5",
              "san": "9. Ne5",
              "note": "Knight to e5!"
            },
            {
              "from": "c8",
              "to": "b7",
              "san": "9... Bb7",
              "note": "Develops"
            },
            {
              "from": "d1",
              "to": "f3",
              "san": "10. Qf3",
              "note": "Queen to kingside"
            }
          ]
        }
      },
      {
        "type": "check",
        "concept": "bg3-trade",
        "question": "In the line above, why did White play 7.Bg3 instead of trading bishops on d6?",
        "options": [
          {
            "text": "To keep the active f4-bishop, which is a key piece in the London System.",
            "correct": true,
            "insight": "Correct! The bishop on f4 is the London's strength; trading it away would weaken White's position."
          },
          {
            "text": "Because Black's bishop on d6 was threatening checkmate.",
            "correct": false,
            "miss": "bg3-trade",
            "insight": "No, there was no checkmate threat. White preserves the bishop because it's valuable long-term."
          },
          {
            "text": "To avoid losing a pawn on b2.",
            "correct": false,
            "miss": "bg3-trade",
            "insight": "Trading bishops doesn't affect b2. White sidesteps to keep the active bishop, not to defend a pawn."
          }
        ]
      },
      {
        "type": "check",
        "concept": "move-order",
        "question": "Why is playing 2.Bf4 before 2.Nf3 recommended in the London System?",
        "options": [
          {
            "text": "Because 2.Nf3 allows Black to play ...c5 and simplify into a comfortable position.",
            "correct": true,
            "insight": "Correct! After 2.Nf3 c5 3.Bf4 cxd4 4.Nxd4 Nd7, Black gets easy play. 2.Bf4 avoids this."
          },
          {
            "text": "Because the knight on f3 blocks the bishop's development.",
            "correct": false,
            "miss": "move-order",
            "insight": "The knight doesn't block—it's a normal square. The issue is the ...c5 simplification, not the knight's placement."
          },
          {
            "text": "Because 2.Bf4 threatens immediate checkmate.",
            "correct": false,
            "miss": "move-order",
            "insight": "No, 2.Bf4 doesn't threaten checkmate. It's a developing move that keeps flexibility."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Summary: Handle ...c5 and ...Qb6 with Confidence",
        "body": "Remember: play <strong>2.Bf4</strong> first to keep the initiative. When Black hits b2 with ...Qb6, don't panic—defend or counter-attack. The London is solid but requires understanding these key moments. You're ready to face Black's sharpest test!"
      }
    ]
  },
  {
    "id": "london-bishop-choice",
    "title": "Bd3 vs Be2: Choosing Your Light-Squared Bishop",
    "subtitle": "When to aim at h7 and when to dodge the fianchetto",
    "steps": [
      {
        "type": "teach",
        "title": "The Bishop's Two Homes",
        "body": "Your light-squared bishop can go to d3 (pointing at h7) or e2 (more flexible). The choice depends on Black's setup — especially if Black fianchettoes with ...g6, which blunts the h7 attack."
      },
      {
        "type": "teach",
        "title": "Bd3: The Aggressive Default",
        "body": "When Black plays ...d5, ...e6, and ...Nf6 (the classical Queen's-Gambit-like structure), Bd3 is ideal. It aims at h7, supports a future e4 break, and combines with Ne5 for a Greek-gift sacrifice."
      },
      {
        "type": "check",
        "concept": "bd3-default",
        "question": "In the classical setup (Black plays ...d5, ...e6, ...Nf6), why is Bd3 the best square for White's light-squared bishop?",
        "options": [
          {
            "text": "It aims at h7, supporting a kingside attack and the e4 break",
            "correct": true,
            "insight": "Correct! Bd3 points at h7 and works with Ne5 for attacking chances."
          },
          {
            "text": "It blocks the e3 pawn, which is always good",
            "correct": false,
            "miss": "bd3-default",
            "insight": "Blocking a pawn is not a reason; the bishop's diagonal to h7 is the key."
          },
          {
            "text": "It defends the b2-pawn from ...Qb6",
            "correct": false,
            "miss": "bd3-default",
            "insight": "Bd3 does not defend b2; the b2-pawn is still loose after Bf4."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Be2: When Black Fianchettoes",
        "body": "If Black plays ...g6 and ...Bg7 (King's-Indian or Grünfeld style), the ...g6 pawn shields h7, making Bd3 less useful. Switch to Be2, which can later go to f3 or support an e4 break."
      },
      {
        "type": "teach",
        "title": "Board Walkthrough: Be2 vs Fianchetto",
        "body": "Watch how White chooses Be2 after Black's ...g6 setup, keeping flexibility.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "Start the London"
            },
            {
              "from": "d7",
              "to": "d5",
              "san": "1... d5",
              "note": "Classical reply"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "2... Nf6",
              "note": "Develops"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Pawn triangle"
            },
            {
              "from": "g7",
              "to": "g6",
              "san": "3... g6",
              "note": "Fianchetto signal"
            },
            {
              "from": "g1",
              "to": "f3",
              "san": "4. Nf3",
              "note": "Knight out"
            },
            {
              "from": "f8",
              "to": "g7",
              "san": "4... Bg7",
              "note": "Fianchetto"
            },
            {
              "from": "f1",
              "to": "e2",
              "san": "5. Be2",
              "note": "Be2, not Bd3"
            }
          ]
        }
      },
      {
        "type": "check",
        "concept": "be2-fianchetto",
        "question": "Why does White play Be2 instead of Bd3 when Black has fianchettoed with ...g6 and ...Bg7?",
        "options": [
          {
            "text": "Because ...g6 blocks the h7 diagonal, so Bd3 loses its attacking purpose",
            "correct": true,
            "insight": "Correct! The ...g6 pawn shields h7, making Bd3 less useful; Be2 is more flexible."
          },
          {
            "text": "Because Be2 is always better than Bd3 in any position",
            "correct": false,
            "miss": "be2-fianchetto",
            "insight": "No, Bd3 is better in many positions; the choice depends on Black's setup."
          },
          {
            "text": "Because Be2 defends the b2-pawn from ...Qb6",
            "correct": false,
            "miss": "be2-fianchetto",
            "insight": "Be2 does not defend b2; the b2-pawn is still loose after Bf4."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Board Walkthrough: Bd3 in Action",
        "body": "Here White uses Bd3 against the classical setup, building toward a kingside attack.",
        "board": {
          "startFen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
          "line": [
            {
              "from": "d2",
              "to": "d4",
              "san": "1. d4",
              "note": "Start"
            },
            {
              "from": "d7",
              "to": "d5",
              "san": "1... d5",
              "note": "Classical"
            },
            {
              "from": "c1",
              "to": "f4",
              "san": "2. Bf4",
              "note": "Active bishop"
            },
            {
              "from": "g8",
              "to": "f6",
              "san": "2... Nf6",
              "note": "Develops"
            },
            {
              "from": "e2",
              "to": "e3",
              "san": "3. e3",
              "note": "Pawn triangle"
            },
            {
              "from": "e7",
              "to": "e6",
              "san": "3... e6",
              "note": "Solid"
            },
            {
              "from": "g1",
              "to": "f3",
              "san": "4. Nf3",
              "note": "Knight"
            },
            {
              "from": "c7",
              "to": "c5",
              "san": "4... c5",
              "note": "Challenge d4"
            },
            {
              "from": "c2",
              "to": "c3",
              "san": "5. c3",
              "note": "Support d4"
            },
            {
              "from": "b8",
              "to": "c6",
              "san": "5... Nc6",
              "note": "Develop"
            },
            {
              "from": "b1",
              "to": "d2",
              "san": "6. Nbd2",
              "note": "Standard"
            },
            {
              "from": "f8",
              "to": "d6",
              "san": "6... Bd6",
              "note": "Trade offer"
            },
            {
              "from": "f4",
              "to": "g3",
              "san": "7. Bg3",
              "note": "Sidestep trade"
            },
            {
              "from": "e8",
              "to": "g8",
              "san": "7... O-O",
              "note": "Castle"
            },
            {
              "from": "f1",
              "to": "d3",
              "san": "8. Bd3",
              "note": "Aim at h7"
            }
          ]
        }
      },
      {
        "type": "check",
        "concept": "black-setups",
        "question": "Black has played ...g6 and ...Bg7 (fianchetto). Which setup does this resemble, and how should White adjust?",
        "options": [
          {
            "text": "King's-Indian / Grünfeld style; White should prefer Be2",
            "correct": true,
            "insight": "Correct! The fianchetto signals a King's-Indian or Grünfeld setup; Be2 is better than Bd3."
          },
          {
            "text": "Classical Queen's-Gambit style; White should play Bd3",
            "correct": false,
            "miss": "black-setups",
            "insight": "No, the fianchetto with ...g6 is not the classical setup; Bd3 is less effective here."
          },
          {
            "text": "It doesn't matter; White always plays Bd3",
            "correct": false,
            "miss": "black-setups",
            "insight": "Playing Bd3 on autopilot is a common mistake; the fianchetto requires Be2."
          }
        ]
      },
      {
        "type": "teach",
        "title": "Summary: Choose Wisely",
        "body": "Remember: Bd3 vs Be2 is a judgment call. Against classical setups (no ...g6), use Bd3 to aim at h7. Against fianchetto setups (...g6/...Bg7), switch to Be2. Never play on autopilot — your bishop's square can make or break your attack."
      }
    ]
  }
];

if (typeof window !== "undefined") window.COURSE_LESSONS = COURSE_LESSONS;
